name: whale_detector
description: Binance Whale Accumulation Detector
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.0
  flutter_local_notifications: ^17.0.0
  http: ^1.2.0

flutter:
  uses-material-design: true
